/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * regi.java
 *
 
 */

package bank_managment_system;
import java.sql.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
/**
 *
 * @author Sumu
 */
public class regi extends javax.swing.JFrame {
public DatabaseTest_1 dt;
    
    public regi(DatabaseTest_1 dt) {
        this.dt=dt;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(447, 530));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bank_managment_system.Bank_managment_systemApp.class).getContext().getResourceMap(regi.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 90, 80, 20);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 140, 80, 20);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 190, 80, 20);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 240, 80, 20);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 290, 80, 20);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 340, 80, 20);

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 390, 80, 20);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 380, 200, 40);

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 80, 200, 40);

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 130, 200, 40);

        jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 180, 200, 40);

        jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 230, 200, 40);

        jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
        jTextField6.setName("jTextField6"); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 280, 200, 40);

        jTextField7.setText(resourceMap.getString("jTextField7.text")); // NOI18N
        jTextField7.setName("jTextField7"); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(170, 330, 200, 40);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 430, 120, 40);

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 50, 160, 30);

        jLabel11.setIcon(resourceMap.getIcon("jLabel11.icon")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 30, 310, 450);

        jLabel12.setIcon(resourceMap.getIcon("jLabel12.icon")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 430, 510);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
/*
            NID=jTextField2.getText();
           USername=jTextField3.getText();
           Password=jTextField4.getText();
          Secw=jTextField5.getText();
          Contact=jTextField6.getText();
          Email=jTextField7.getText();
          Gender=jTextField1.getText();

 */
        

   /*

        if(jTextField2.getText().equals("") && jTextField3.getText().equals("")&& jTextField4.getText().equals("")&& jTextField5.getText().equals("")&& jTextField6.getText().equals("")&& jTextField7.getText().equals("")&& jTextField1.getText().equals(""))
         {

              UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
          else if(jTextField2.getText().equals(""))
         {
                          UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
        else if(jTextField3.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);

         }
        else if(jTextField4.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField5.getText().equals(""))
         {
UIManager UI=new UIManager();
              UI.put("OptionPane.background", Color.red);
             UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField6.getText().equals(""))
         {
         UIManager UI=new UIManager();
         UI.put("OptionPane.background", Color.red);
         UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField7.getText().equals(""))
         {
            UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.red);
            UI.put("Panel.background", Color.red);

         JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField1.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.red);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }


        else
         {
           NID=jTextField2.getText();
           USername=jTextField3.getText();
           Password=jTextField4.getText();
          Secw=jTextField5.getText();
          Contact=jTextField6.getText();
          Email=jTextField7.getText();
          Gender=jTextField1.getText();
          

         }


*/

          try{

               ResultSet rs = dt.dbc.searchDB("select * from times");

                    if(jTextField2.getText().equals("") && jTextField3.getText().equals("")&& jTextField4.getText().equals("")&& jTextField5.getText().equals("")&& jTextField6.getText().equals("")&& jTextField7.getText().equals("")&& jTextField1.getText().equals(""))
         {

              UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
          else if(jTextField2.getText().equals(""))
         {
                          UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
        else if(jTextField3.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);

         }
        else if(jTextField4.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField5.getText().equals(""))
         {
UIManager UI=new UIManager();
              UI.put("OptionPane.background", Color.red);
             UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField6.getText().equals(""))
         {
         UIManager UI=new UIManager();
         UI.put("OptionPane.background", Color.red);
         UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField7.getText().equals(""))
         {
            UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.red);
            UI.put("Panel.background", Color.pink);

         JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }
else if(jTextField1.getText().equals(""))
         {
             UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.red);
        UI.put("Panel.background", Color.pink);

        JOptionPane.showMessageDialog(null,"Fill all","RECHECK",JOptionPane.INFORMATION_MESSAGE);
         }


        else
         {
           NID=jTextField2.getText();
           USername=jTextField3.getText();
           Password=jTextField4.getText();
          Secw=jTextField5.getText();
          Contact=jTextField6.getText();
          Email=jTextField7.getText();
          Gender=jTextField1.getText();

              dt.dbc.updateDB("insert into times values('"+NID+"','"+USername+"','"+Password+"','"+Secw+"','"+Contact+"','"+Email+"','"+Gender+"')");
              dt.dbc.updateDB("insert into news values('"+NID+"','"+USername+"','"+Password+"','"+Secw+"','"+Contact+"','"+Email+"','"+Gender+"')");
              this.setVisible(false);
              log_in t=new log_in();
              t.setVisible(true);
              Bank_managment_systemApp.getApplication().getMainFrame().setVisible(false);

               UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.pink);
            UI.put("Panel.background", Color.pink);

            JOptionPane.showMessageDialog(null,"registration successful","ok",JOptionPane.INFORMATION_MESSAGE);


         }
              

        /*
              dt.dbc.updateDB("insert into times values('"+NID+"','"+USername+"','"+Password+"','"+Secw+"','"+Contact+"','"+Email+"','"+Gender+"')");
              dt.dbc.updateDB("insert into news values('"+NID+"','"+USername+"','"+Password+"','"+Secw+"','"+Contact+"','"+Email+"','"+Gender+"')");
              this.setVisible(false);
              log_in t=new log_in();
              t.setVisible(true);
              Bank_managment_systemApp.getApplication().getMainFrame().setVisible(false);

               UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.pink);
            UI.put("Panel.background", Color.pink);

            JOptionPane.showMessageDialog(null,"registration successful","ok",JOptionPane.INFORMATION_MESSAGE);

*/

              //jp.showMessageDialog(jf, "registration successful");
          }catch(Exception e){

               UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.red);
            UI.put("Panel.background", Color.red);

            JOptionPane.showMessageDialog(null,"registration not successful","warning",JOptionPane.INFORMATION_MESSAGE);
               

              //jp.showMessageDialog(jf, "registration not successful");
          }



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
   
    String NID=new String();
    String USername=new String();
    String Password=new String();
    String Secw=new String();
    String Contact=new String();
    String Email=new String();
    String Gender=new String();
    public javax.swing.JOptionPane jp;
    public javax.swing.JFrame jf;

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration



/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
*/
}
